### ISSUE TITLE
telegraf-keyboard

### ISSUE THREAD

**Issue by RealPeha** [incetarik/telegram-bot-framework#3]
Hi!

I want to remove telegraf-keyboard package from npm, but your library depends on it. Could you remove it from the dependencies and replace it with, for example, [telegram-keyboard](https://github.com/RealPeha/telegram-keyboard)?

**Comment by incetarik** [comment]
@RealPeha Yeah of course, thank you for notifying.

**Comment by RealPeha** [comment]
@incetarik Please notify when you do this 😉

**Comment by RealPeha** [comment]
@incetarik so what about this?

**Comment by incetarik** [comment]
@RealPeha Done.
